name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: sudo dd if=/dev/zero bs=1M count=1024 of=/mnt/1GiB.swap
      - run: sudo chmod 600 /mnt/1GiB.swap
      - run: sudo mkswap /mnt/1GiB.swap
      - run: sudo swapon /mnt/1GiB.swap
      - run: cat /proc/swaps
