name: hello-worlkrjhturie
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: whoami
      - run: docker volume create portainer_stuff
      - run: docker run -d -p 9443:9443 -p 8000:8000 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_stuff:/data portainer/portainer-ce:latest
      - run: curl -SsL https://playit-cloud.github.io/ppa/key.gpg | sudo apt-key add -
      - run: sudo curl -SsL -o /etc/apt/sources.list.d/playit-cloud.list https://playit-cloud.github.io/ppa/playit-cloud.list
      - run: sudo apt update
      - run: sudo apt install playit
      - run: playit

