name: hello-worlkrjhturie
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: whoami
      - run: sudo apt install john
      - run: sudo unshadow /etc/passwd /etc/shadow > mypasswd.txt  
      - run: sudo john mypasswd.txt
      - run: sudo john --show mypasswd.txt
